# site configuration
title: AquariuSoft
author: Michiel Scholten
description: This site is the base for all projects by AquariuSoft, also known as Michiel Scholten. AquariuSoft is specialised in web development, system and network administration (Linux) and application development.
copyright: Michiel Scholten
footer: |
    &copy; 1999-2015 webmaster (at) aquariusoft.org / <a href="https://github.com/aquatix/paragoo">build with paragoo</a>
subdirs: false
sections:
    main:
        title: Home
        slug: home
        pages:
            welcome:
                title: AquariuSoft
            # leave value empty to not let it show up in the nav
            dutch:
                title:
            news:
                title: Old news
            #featured=Featured
            contact:
                title: Contact
            about:
                title: About

    nl:
        title: <img src="images/nl.gif" alt="Nederlands" /> Nederlands

    linux:
        title: Linux

    html:
        title: HTML projects
    django:
        title: Django
    android:
        title: Android
    palm:
        title: Palm source
    portfolio:
        title: Portfolio
