# site configuration
title: AquariuSoft
author: Michiel Scholten
description: This site is the base for all projects by AquariuSoft, also known as Michiel Scholten. AquariuSoft is specialised in web development, system and network administration (Linux) and application development.
logo: <img style="vertical-align:middle" src="/images/aquariusoft_org_white.png" alt="aquariusoft.org logo" />
# Disable 'normal'/'mobile' navigation switch
mobiletoggle: False
copyright: Michiel Scholten
footer: |
    &copy; 1999-2016 webmaster (at) aquariusoft.org // <a href="https://github.com/aquatix/paragoo">build with paragoo</a>
about_title: About AquariuSoft
about: |
    AquariuSoft.org is the project website of Michiel Scholten, collecting projects and howtos from various aspects of technological life.
subdirs: false
errorpage: |
    <p>If you are looking for the overload feedreader, please note <a href="page/html/overload">it has been discontinued</a>. It might come back -- rewritten in Python/Django for example -- but not soon.</p>
    <p>The Windows section is gone, as the applications were unmaintained and quite antique.</p>
    <p>Also, the forum has been discontinued because of disuse.</p>
    <p>If you notice something missing, don't hesitate to <a href="page/main/contact/">contact me</a>.</p>

linkblocks:
    block1:
        title: Photography
        links:
            gallery:
                title: Gallery
                url: http://aquariusoft.org/photo/
            photolog:
                title: Photolog
                url: http://photolog.aquariusoft.org/
    block2:
        title: Weblogs
        links:
            dammit:
                title: dammIT
                url: http://dammit.nl/
            familiescholten:
                title: Familie Scholten
                url: http://familiescholten.net/

replacements:
    # Text to replace in rendered pages, for example to make a uri absolute
    href="image/:
        href="/image/
    src="image/:
        src="/image/
    href="images/:
        href="/images/
    src="images/:
        src="/images/
    href="files/:
        href="/files/

sections:
    main:
        title: Home
        slug: home
        pages:
            welcome:
                title: Welcome to aquariusoft.org
                navtitle: Welcome
            # leave value empty to not let it show up in the nav
            #dutch:
            #    title:
            news:
                title: News archive
            #featured=Featured
            contact:
                title: Contact
            about:
                title: About

    linux:
        title: Linux
        pages:

            backup:
                title: backup scripts
                description: A howto on periodically backing up import data from your server(s)
            irssi:
                title: irssi
            mellow:
                title: Mellow Subsonic
            svnsync:
                title: svn remote sync
            upgradefirmwareinlinux:
                title: firmware upgrading
            # if value is empty, it will not show up in the sub navigation
            # or set visible: false
            aquamorph:
                title: "⌚ aquamorph livecd"
            aquamorph_news:
                title:
            aquamorph_packages:
                title:
            aquamorph_todo:
                title:
            livecd_howto:
                title: ⌚ livecd HOWTO
            wpasupplicant4vu:
                title: ⌚ wpasupplicant for VU
                navtitle: ⌚ wpasupplicant
            xsupplicant4vu:
                title: ⌚ xsupplicant for VU
                navtitle: ⌚ xsupplicant


    html:
        title: Web projects
        pages:
            blog:
                title: "simplog/kontent: weblog software"
                navtitle: weblog software
            paragoo:
                title: paragoo site generator
                navtitle: paragoo
            qik:
                title: ⌚ Qik framework
            htmlmodules:
                title: ⌚ HTML modules
            iplugs:
                title: ⌚ iplugs
            overload:
                title: ⌚ overload information manager
                navtitle: ⌚ overload
    python:
        title: Python modules
        pages:
            nsapi:
                title: NS API
                slug: nsapi
            utilkit:
                title: utilkit library
                navtitle: utilkit
    django:
        title: Django
        pages:
            config:
                title: Configure
            djangocon:
                title: DjangoCon
    android:
        title: Android
        pages:
            news:
                title: News
            essentials:
                title: Essential apps
            list:
                title: Cool List
            root:
                title: Rooting and updating rooted devices
                navtitle: Rooting
            certs:
                title: Install certificates
    palm:
        title: Palm source
        pages:
            bluetooth_linux:
                title: bluetooth and Linux
    portfolio:
        title: Portfolio

    nl:
        title: <img src="/images/nl.gif" alt="Nederlands" /> Nederlands
        pages:
            home:
                title: Welkom
            portfolio:
                title: Portfolio
            contact:
                title: Contact
