# site configuration
main:
    name: Home

    welcome:
        name: AquariuSoft
    # leave value empty to not let it show up in the nav
    dutch:
        name:
    news:
        name: Old news
    #featured=Featured
    contact:
        name: Contact
    about:
        name: About

nl:
    name: <img src="images/nl.gif" alt="Nederlands" /> Nederlands

linux:
    name: Linux

html:
    name: HTML projects
django:
    name: Django
android:
    name: Android
palm:
    name: Palm source
portfolio:
    name: Portfolio
