# site configuration
title: AquariuSoft
author: Michiel Scholten
description: This site is the base for all projects by AquariuSoft, also known as Michiel Scholten. AquariuSoft is specialised in web development, system and network administration (Linux) and application development.
copyright: Michiel Scholten
footer: |
    &copy; 1999-2015 webmaster (at) aquariusoft.org // <a href="https://github.com/aquatix/paragoo">build with paragoo</a>
subdirs: false
errorpage: |
    <p>If you are looking for the overload feedreader, please note <a href="page/html/overload">it has been discontinued</a>. It might come back -- rewritten in Python/Django for example -- but not soon.</p>
    <p>The Windows section is gone, as the applications were unmaintained and quite antique.</p>
    <p>Also, the forum has been discontinued because of disuse.</p>
    <p>If you notice something missing, don't hesitate to <a href="page/main/contact/">contact me</a>.</p>
sections:
    main:
        title: Home
        slug: home
        pages:
            welcome:
                title: Welcome
            # leave value empty to not let it show up in the nav
            dutch:
                title:
            news:
                title: Old news
            #featured=Featured
            contact:
                title: Contact
            about:
                title: About

    nl:
        title: <img src="/images/nl.gif" alt="Nederlands" /> Nederlands
        pages:
            home:
                title: Welkom
            portfolio:
                title: Portfolio
            contact:
                title: Contact

    linux:
        title: Linux
        pages:

            # if value is empty, it will not show up in the sub navigation
            # or set visible: false
            aquamorph:
                title: "aquamorph livecd"
            aquamorph_news:
                title:
            aquamorph_packages:
                title:
            aquamorph_todo:
                title:
            backup:
                title: backup scripts
                description: A howto on periodically backing up import data from your server(s)
            irssi:
                title: irssi
            livecd_howto:
                title: livecd HOWTO
            mellow:
                title: Mellow Subsonic
            svnsync:
                title: svn remote sync
            upgradefirmwareinlinux:
                title: firmware upgrading
            wpasupplicant4vu:
                title: wpasupplicant for VU
            xsupplicant4vu:
                title: xsupplicant for VU


    html:
        title: Web projects
        pages:
            qik:
                title: Qik site framework
            blog:
                title: "simplog: weblog software"
            htmlmodules:
                title: HTML modules
            iplugs:
                title: iplugs
            overload:
                title: overload information manager
    django:
        title: Django
        pages:
            config:
                title: Configure
            djangocon:
                title: DjangoCon
    android:
        title: Android
        pages:
            news:
                title: News
            essentials:
                title: Essential apps
            list:
                title: Cool List
            certs:
                title: Install certificates
    palm:
        title: Palm source
        pages:
            bluetooth_linux:
                title: bluetooth and Linux
    portfolio:
        title: Portfolio
